export const ADD_TODO_TO_STATE = "ADD_TODO_TO_STATE";
export const UPDATE_CHECKED_TODO_IN_STATE = "UPDATE_CHECKED_TODO_IN_STATE";
export const DELETE_TODO_IN_STATE = "DELETE_TODO_IN_STATE";
export const UPDATE_TODO_TITLE_IN_STATE = "UPDATE_TODO_TITLE_IN_STATE";
export const FIRST_TODO_IN_STATE = "FIRST_TODO_IN_STATE";
export const PAGE_UPDATE_IN_STATE = "PAGE_UPDATE_IN_STATE";
